# 仅对原始样本进行单次增强方式，一个抠图不涉及两次及以上的连续增强，为了保障生成样本的真实性，不考虑对抠图样本的颜色变换
samples_path: "samples" # 原始样本路径，默认存放抠图样本的文件夹名称
output_path: "AugSamples" # 生成样本路径，默认存放增强样本的文件夹名称，不要更改！！！
rotation_angle: [45, 90, 135, 180, 225, 270, 315] # 对于抠图样本生成固定的旋转角度，修改数值即可
up_ratio: [2, 3, 4] # 对于抠图样本生成固定的放大比例，修改数值即可
down_ratio: [2, 3, 4] # 对于抠图样本生成固定的缩小比例，修改数值即可
light_factor: [0.5, 0.75, 1.0, 1.25, 1.5] # 对于抠图样本生成固定的亮度比例，修改数值即可